name: Deploy Debug Lab via FTP

on:
  push:
    branches:
      - main  # O deploy acontece sempre que você der push na main

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files to HostGator
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./public_html/  # Caminho padrão na HostGator1
        port: 21 # forçar porta